import { AuthProvider } from "@/context/auth-context";
import type { Metadata } from "next";
import { Inter, Poppins } from 'next/font/google'
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en" className={`${inter.variable} ${poppins.variable} antialiased`}>
        <body
          className="font-inter"
        >
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
